apiVersion: v1
kind: Pod
metadata:
  name: scenario5-oom
spec:
  containers:
  - name: memory-hog
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "200M"]
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"    # tries 200MB but limit is 100MB