# ServiceAccount for backend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: mini-app
---
# Role — backend can read configmaps and secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: mini-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: mini-app
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: mini-app
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io